### ISSUE TITLE
How can python-wasi support external dependencies

### ISSUE THREAD

**Issue by LijieZhang1998** [singlestore-labs/python-wasi#12]
Hi,

I'm trying to run a piece python code that imports [pymongo](https://github.com/mongodb/mongo-python-driver) to connect my mongodb. Do you know what I should do to support this dependency? For now I got the following error. I didn't install this dependency anywhere because I don't know where and how I can install it so `wasi-python.wasm` can load it. Noticed [this](https://github.com/singlestore-labs/python-wasi/blob/main/docker/Dockerfile#L72C17-L72C17) part in Docker file to include `lzma` package. But I'm not sure how to deal with pymongo package. I'm pretty new to wasm/wasi. Any help is appreciated. 

```
Traceback (most recent call last):
  File "//./testfiles/ping.py", line 1, in <module>
    from pymongo.mongo_client import MongoClient
ModuleNotFoundError: No module named 'pymongo'
```

**Comment by kesmit13** [comment]
If it is a pure Python package, you could install it to a directory using the same version of Python on your desktop machine, map that directory into your Wasm instance, then add the directory to your Python path in the instance. However, in this case, it wouldn't work because this package requires networking. Wasm currently doesn't support networking since that breaks the security sandbox. There will likely be ways of supporting networking in the future.
